# Application bindings
$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, K, Kitty, exec, uwsm app -- kitty
bindd = SUPER SHIFT, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = CTRL SHIFT, ESCAPE, HTop, exec, omarchy-launch-tui htop
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus "^obsidian$" "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, slash, Passwords, exec, uwsm app -- bitwarden-desktop
bindd = SUPER SHIFT, V, VS Code, exec, omarchy-launch-tui code
bindd = SUPER SHIFT, Z, Zoho Mail, exec, uwsm app -- zoho-mail-desktop

bindd = SUPER SHIFT ALT, G, GitHub, exec, omarchy-launch-webapp "https://github.com"
bindd = SUPER SHIFT, M, MonkeyType, exec, omarchy-launch-webapp "https://monkeytype.com"
bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT, C, ClaudeAi, exec, omarchy-launch-webapp "https://claude.ai"
bindd = SUPER SHIFT ALT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
bindd = SUPER SHIFT, E, Gmail, exec, omarchy-launch-webapp "https://mail.google.com"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT, T, Todoist, exec, omarchy-launch-webapp "https://app.todoist.com"
bindd = SUPER SHIFT, G, Google Search, exec, uwsm app -- brave --incognito google.com

# bindd = SUPER SHIFT, F, Full Screen, fullscreen
bindd = SUPER, Q,Close Window, killactive
unbind = SUPER, TAB
bindd = SUPER, TAB, Former workspace, workspace, previous

bindd = SUPER SHIFT, W, Window Info, exec, notify-send "Window Info" "$(hyprctl activewindow -j | jq -r '.class')"

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER SHIFT, Space
# bindd = SUPER SHIFT, SPACE, Omarchy menu, exec, omarchy-menu

unbind = SUPER, W
